# Copyright 2018 DigitalOcean
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: point DNS at the paddles node
  lineinfile:
    path: /etc/systemd/resolved.conf
    line: "DNS={{ paddles_node_ip }}"
    regexp: "DNS="
    state: present

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted

- name: install head node packages
  apt:
    update_cache: yes
    name:
      - git
      - python-dev
      - python-pip
      - python-virtualenv
      - libevent-dev
      - python-libvirt
      - beanstalkd
      - libssl-dev
      - libev-dev
      - libvirt-dev
      - libmysqlclient-dev
      - libffi-dev
      - libyaml-dev
    state: present

- name: create teuthology config file
  template:
    src: teuthology.yaml.j2
    dest: /etc/teuthology.yaml
    mode: 0644

- name: disable ssh host key checking
  lineinfile:
    path: /etc/ssh/ssh_config
    line: "    StrictHostKeyChecking no"
    regexp: "StrictHostKeyChecking"
    state: present

- name: create teuthology system user
  user:
    name: teuthology
    shell: /bin/bash
    state: present

- name: create teuthworker system user
  user:
    name: teuthworker
    shell: /bin/bash
    state: present

- name: enable passwordless sudo for teuthology and teuthworker
  lineinfile:
    dest: /etc/sudoers.d/teuthology
    line: "{{ item }} ALL=(root) NOPASSWD: ALL"
    create: yes
  with_items:
    - "teuthology"
    - "teuthworker"

- name: create .ssh directory for teuthology
  become: yes
  become_user: teuthology
  file:
    path: /home/teuthology/.ssh
    state: directory
    mode: 0700

- name: place teuthology user ssh key
  become: yes
  become_user: teuthology
  copy:
    dest: /home/teuthology/.ssh/id_rsa
    mode: 0600
    content: |
      {{ ssh_priv_key }}

- name: create .ssh directory for teuthworker
  become: yes
  become_user: teuthworker
  file:
    path: /home/teuthworker/.ssh
    state: directory
    mode: 0700

- name: place teuthworker user ssh key
  become: yes
  become_user: teuthworker
  copy:
    dest: /home/teuthworker/.ssh/id_rsa
    mode: 0600
    content: |
      {{ ssh_priv_key }}

- name: create teuthology src directory
  become: yes
  become_user: teuthology
  file:
    path: /home/teuthology/src
    state: directory

- name: clone teuthology for teuthology
  become: yes
  become_user: teuthology
  git:
    repo: https://github.com/ceph/teuthology.git
    dest: /home/teuthology/src/teuthology_master
    version: master

- name: bootstrap teuthology for teuthology
  become: yes
  become_user: teuthology
  command: ./bootstrap
  args:
    creates: /home/teuthology/src/teuthology_master/virtualenv
    chdir: /home/teuthology/src/teuthology_master

- name: automatically activate virutalenv for teuthology
  become: yes
  become_user: teuthology
  lineinfile:
    path: /home/teuthology/.profile
    line: "source $HOME/src/teuthology_master/virtualenv/bin/activate"
    state: present

- name: create overrides file for teuthology
  become: yes
  become_user: teuthology
  copy:
    src: overrides.yml
    dest: /home/teuthology/overrides.yml
    mode: 0644

- name: create teuthworker directories
  become: yes
  become_user: teuthworker
  file:
    path: "/home/teuthworker/{{ item }}"
    state: directory
  with_items:
    - "src"
    - "bin"
    - "archive/worker_logs"

- name: clone teuthology for teuthworker
  become: yes
  become_user: teuthworker
  git:
    repo: https://github.com/ceph/teuthology.git
    dest: /home/teuthworker/src/teuthology_master
    version: master

- name: bootstrap teuthology for teuthworker
  become: yes
  become_user: teuthworker
  command: ./bootstrap
  args:
    creates: /home/teuthworker/src/teuthology_master/virtualenv
    chdir: /home/teuthworker/src/teuthology_master

- name: get worker start script
  become: yes
  become_user: teuthworker
  get_url:
    url: https://raw.githubusercontent.com/ceph/teuthology/master/docs/_static/worker_start.sh
    dest: /home/teuthworker/bin/worker_start
    mode: 0755

- name: create worker startup script
  become: yes
  become_user: teuthworker
  template:
    src: start-teuth-worker.sh.j2
    dest: /home/teuthworker/bin/start-teuth-worker.sh
    mode: 0755

- name: create worker service
  copy:
    src: teuth-worker.service
    dest: /etc/systemd/system/teuth-worker.service
    mode: 0644

- name: enable and start worker service
  systemd:
    name: teuth-worker
    state: started
    enabled: yes

- name: register node with paddles DNS
  become: yes
  become_user: teuthology
  command: >
    ssh -oStrictHostKeyChecking=no -i /home/teuthology/.ssh/id_rsa root@{{ paddles_public_ip }}
    "echo '{{ ansible_host }} head-node.{{ lab_domain }}' >> /etc/hosts"
  changed_when: true

- name: create log server service
  copy:
    src: log-server.service
    dest: /etc/systemd/system/log-server.service
    mode: 0644

- name: enable and start log server service
  systemd:
    name: log-server
    state: started
    enabled: yes

- name: update paddles config with log server address
  become: yes
  become_user: teuthology
  command: >
    ssh -oStrictHostKeyChecking=no -i /home/teuthology/.ssh/id_rsa root@{{ paddles_public_ip }}
    "sed -i 's/REPLACE-ME-WITH-HEAD-NODE-ADDR/{{ ansible_host }}/' /home/paddles/paddles/config.py"
  changed_when: true

- name: restart paddles
  become: yes
  become_user: teuthology
  command: >
    ssh -oStrictHostKeyChecking=no -i /home/teuthology/.ssh/id_rsa root@{{ paddles_public_ip }}
    "systemctl restart paddles.service"
  changed_when: true
